# Surge AI Sentiment Analysis project (Binary Classification)
name: surge_ai
experiment: baseline
params: 
    common:
        embed_dim: 128
        hidden_dim: 256
        lstm_n_layers: 2
        lstm_bidirectional: true
        lstm_dropout_rate: 0.1
    train:
        batch_size: 32
        shuffle: true
        epochs: 500
        learning_rate: 0.0025
        optimizer: adam
    validate:
        batch_size: 16
        shuffle: false
